# Generated by Django 4.1.5 on 2023-01-21 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AllFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.FileField(upload_to='media', verbose_name='Transaction File')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reciever_name', models.CharField(max_length=255, verbose_name='Reciever Name')),
                ('account_number', models.IntegerField(verbose_name='Account Number')),
                ('ammount', models.IntegerField(verbose_name='Ammount')),
                ('method', models.CharField(choices=[('Payment', 'payment'), ('Withdraw', 'withdraw')], max_length=255, verbose_name='Transaction Method')),
            ],
        ),
    ]
